### ISSUE TITLE
Fix Launching

### ISSUE THREAD

**Issue by GalaxyHackerNewer** [SuperHackio/WiiExplorer#16]
I update my graphic card to AMD A6-6310 APU with AMD Radeon R4 Graphics   but after tons of uppdate of my windows 10 windows insider the software stop working fix quickly thanks @SuperHackio

**Comment by SuperHackio** [comment]
This gives me no useful information.
Try running WiiExplorer via Command Line (CMD) and see if it gives you an error message.
