### ISSUE TITLE
Option to open .szs files

### ISSUE THREAD

**Issue by gayfrogog** [SuperHackio/WiiExplorer#4]
Program only has the option to show all files or just ARC files. SZS files are also Yaz0 compressed RARC files and as such should also be shown under the show ARC option in the open menu.

**Comment by SuperHackio** [comment]
This feature has been added in V1.2.5.0
![image](https://user-images.githubusercontent.com/44330283/98978076-3f5f3880-24ce-11eb-83b4-950b9392c23b.png)
