### ISSUE TITLE
Renaming bug after replace [1.3.1.0]

### ISSUE THREAD

**Issue by Evanbowl** [SuperHackio/WiiExplorer#5]
[This is a minor bug]
I replaced map.col but it came out as map (2).col
![Capture](https://user-images.githubusercontent.com/74565954/99301350-d3f1cf80-281b-11eb-82d9-6348280400ea.PNG)

**Comment by SuperHackio** [comment]
Will investigate immediately

**Comment by SuperHackio** [comment]
The program didn't know that you were replacing the file when it was checking to see if the same file existed already. This has been fixed. and will be present in the next update.
