### ISSUE TITLE
Add proper message box for when the file format is not supported

### ISSUE THREAD

**Issue by ghyujkilop** [SuperHackio/WiiExplorer#6]
When I try to open audiostr.arc which I extracted from The Urbz Sims in the City discs DATA folder, I get this error below.
Any idea how I can extract the files from this .arc?

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Invalid Identifier. Expected "RARC"
   at Hack.io.RARC.RARC.Read(Stream RARCFile) in C:\Users\Hackio\source\repos\Hack.io\Hack.io.RARC\RARC.cs:line 879
   at Hack.io.RARC.RARC..ctor(String filename) in C:\Users\Hackio\source\repos\Hack.io\Hack.io.RARC\RARC.cs:line 60
   at WiiExplorer.MainForm.OpenArchive(String Filename)
   at WiiExplorer.MainForm.OpenToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WiiExplorer
    Assembly Version: 1.4.5.0
    Win32 Version: 1.4.5.0
    CodeBase: file:///D:/SteamLibrary%20(extra%20permissions)/steamapps/common/Dolphin/t00pos/WiiExplorer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Hack.io.YAZ0
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///D:/SteamLibrary%20(extra%20permissions)/steamapps/common/Dolphin/t00pos/lib/Hack.io.YAZ0.DLL
----------------------------------------
Hack.io.YAY0
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/SteamLibrary%20(extra%20permissions)/steamapps/common/Dolphin/t00pos/lib/Hack.io.YAY0.DLL
----------------------------------------
Hack.io.RARC
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///D:/SteamLibrary%20(extra%20permissions)/steamapps/common/Dolphin/t00pos/lib/Hack.io.RARC.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WiiExplorer.resources
    Assembly Version: 1.4.5.0
    Win32 Version: 1.4.5.0
    CodeBase: file:///D:/SteamLibrary%20(extra%20permissions)/steamapps/common/Dolphin/t00pos/lib/en/WiiExplorer.resources.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Hack.io
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/SteamLibrary%20(extra%20permissions)/steamapps/common/Dolphin/t00pos/lib/Hack.io.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by SuperHackio** [comment]
If you open the file in a HEX editor (like HxD), the first 4 bytes to not say 'RARC'
This simply means that the file you are trying to open is not compatible with WiiExplorer. Because it is the sims, I don't imagine that it used Nintendo's In-house development studio tools, but this file is a different type of .arc file. If you show me the first 4 bytes I could see if I know what format it is, but in the end, WiiExplorer will not work with it.

**Comment by SuperHackio** [comment]
Messagebox has been added
