### ISSUE TITLE
[Enhancement] Add Support for SM3DAS Galaxy Arc's

### ISSUE THREAD

**Issue by IonicPixels** [SuperHackio/WiiExplorer#8]
On the Wii, the archives use the magic "RARC" and are Big Endian, as you would likely know. However, the Galaxy archives for 3DAS use the magic "CRAR" and are Little Endian. I'll send you an archive of both games on Discord, open them with a Hex Editor to see what I mean.

**Comment by SuperHackio** [comment]
Hack.io doesn't have Little Endian support built in.
This won't be added to WiiExplorer
